KidsGenius/Models/Course.cs
using System.ComponentModel.DataAnnotations;

namespace KidsGenius.Models
{
    public class Course
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [Display(Name = "Course name")]
        public string Name { get; set; }

        [Display(Name = "Main picture")]
        public string MainPicture { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Header color")]
        public string StyleColor { get; set; }
    }
}

KidsGenius/Controllers/CoursesController.cs
using KidsGenius.DAL;
using KidsGenius.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace KidsGenius.Controllers
{
    public class CoursesController : Controller
    {
        CourseContext db = new CourseContext();

        public ActionResult CoursesList()
        {
            IEnumerable<Course> courses = db.Courses;

            ViewBag.Courses = courses;

            return View();
        }

        public ActionResult Course(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Course course = db.Courses.Find(id);

            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        public ActionResult BuyCourse()
        {


            return View();
        }
    }
}

KidsGenius/Views/Courses/Course.cshtml
@model KidsGenius.Models.Course

@{
    ViewBag.Title = "Course";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<div class="header">*@
<div class="brochure-course-sticky-header-container" id="sticky-header">
    <div class="brochure-course-sticky-header-navigation">
        <div id="button" style="background-image: url(../../Content/images/icons/back-button.png); padding-left: 30px; background-size: contain; background-repeat: no-repeat; padding-bottom: 4px;">
            <a href="/Courses/CoursesList" style="color: #fff!important;">Back to All Courses</a>
        </div>
    </div>
    <div class="brochure-course-sticky-header-actions">
        <button type="button" class="blue buttons-group">Join Course</button>
        <button type="button" onclick="location.href='@Url.Action("Login", "Account")'" class="brochure-course-sticky-header-login invert blue buttons-group">Kid Sign In</button>
    </div>
</div>
@*</div>*@
<div class="brochure-detail-header-container" style="background-color:#@Model.StyleColor; );  color:#39464E">
    <div class="brochure-detail-header-title-wrapper">
        <img alt="presentation" class="brochure-detail-header-background-image" src="@Model.MainPicture" />
    </div>
    <div class="brochure-detail-header-content">
        <div class="brochure-detail-header-video" id="video-container">
            <div class="video-wrapper" id="video-content">
                <div class="video-and-control" id="video-and-control">
                    @*<img src="~/Content/images/icons/large-pause-button.png" style="position:absolute; margin:auto; width:100%; padding: 35%;"/>*@
                    <video class="video-container video">
                        <source src="https://d2ecljqfw49px2.cloudfront.net/courses/127/75c04668-d280-4200-9c5f-abdb0c052e50/72/0d2020901311e694cc05c530818696/original_0.mp4" type="video/mp4">
                    </video>
                    <div class="video-controls-container" id="controls-container">
                        <button type="button" class="play-button circle" id="play-button" style="background-color:#@Model.StyleColor; background-image: url(../../Content/images/icons/play-button.png); background-size: cover"></button>
                        <div class="control-timeline">
                            <div class="video-control-timeline">
                                <div class="video-control-scrubber" id="timeline-scrubber">
                                    <div class="video-time-passed" id="video-passed" style="width:0%; background-color:#@Model.StyleColor; height: inherit; border-radius: inherit;"></div>
                                    <div class="video-control-point" id="timer-point-button" style="left:0px; background-color:#@Model.StyleColor;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="control-fullscreen">
                            <button type="button" class="full-screen-button circle" id="full-screen-button" style="background-color:#@Model.StyleColor">
                                <img class="full-screen-img" src="~/Content/images/icons/full-screen.png" />
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="brochure-detail-header-clickables">
            <div class="brochure-detail-header-details">
                <div class="brochure-detail-subtitle">Fill your own sketchbook with original drawings!</div>
                <div class="brochure-detail-description">
                    Start drawing or grow your talents by learning the creative process of a pro illustrator. You'll feel proud to have a portfolio of your own artwork.
                </div>
            </div>
            <div class="brochure-course-actions">
                <button type="button" onclick="location.href='@Url.Action("Register", "Account", new { id = Model.Id}))'" class="primary" style="color: #@Model.StyleColor!important; background-color: rgb(57, 70, 78); margin-right: 12px;">
                    Try For Free!
                </button>
                <button type="button" class="brochure-course-gift" style="border-color: rgb(57, 70, 78); color: rgb(57, 70, 78);">
                    Gift This Course
                </button>
            </div>
        </div>
    </div>
</div>
<div class="courseLeader" id="courseLeader">
    <div>
        <p>Eva Kee</p>
    </div>
</div>
<div class="description">
    <div class="brochure-course-container">
        <div class="brochure-detail-explanation">
            <div class="brochure-detail-title">
                Ages 8 - 12
            </div>
        </div>
        <div class="brochure-course-requirements">
            <div class="brochure-course-requirement">
                <span class="em emj642">
                </span>No experience necessary
            </div>
            <div class="brochure-course-requirement">
                <span class="em emj1176">
                </span>Pencil and paper required
            </div>
            <div class="brochure-course-requirement">
                <span class="em emj775">
                </span>Work at your own pace
            </div>
        </div>
    </div>

    <div class="brochure-quests-container">
        <div class="brochure-detail-explanation">
            <div class="brochure-detail-title">
                18 Packs
            </div>
            <div class="brochure-detail-explanation-description">
                Packs are the foundation of "Kids Genius" courses.&nbsp; <br />These challenges are designed to help kids achieve mastery by trying.
            </div>
        </div>
        <div class="brochure-quests">
            @for (var i = 1; i <= 18; i++)/*@foreach (var course in 18)*/
            {
                <a class="brochure-quest">
                    <div class="brochure-quest-media">
                        <div class="media-container video" role="button" tabindex="0">
                            <div class="media-image" style="background-image: url('../../Content/images/200w_d.gif');">
                            </div>
                        </div>
                        <div class="brochure-quest-number">
                            @i
                        </div>
                        <div class="brochure-quest-name">
                            Hello
                        </div>
                    </div>
                </a>
            }
        </div>
    </div>
</div>

<script src="~/Content/js/device.js"></script>

<script>
    window.onscroll = function () { myFunction() };

    var stickyHeader = document.getElementById("sticky-header");
    var contentStart = document.getElementById("courseLeader");
    var sticky = contentStart.offsetTop;

    function myFunction() {
        if (window.pageYOffset >= sticky) {
            stickyHeader.classList.add("show");
        } else {
            stickyHeader.classList.remove("show");
        }
    }
</script>

<script>
    var videoEl = document.getElementsByTagName('video')[0],
        videoContainer = document.getElementById('video-container'),
        //videoContent = document.getElementById('video-content'),
        playButton = document.getElementById('play-button'),
        fullScreenButton = document.getElementById('full-screen-button'),
        videoControls = document.getElementById('controls-container'),
        //volumeControl = document.getElementById('volume'),
        timeLine = document.getElementById('timeline-scrubber'),
        videoPassed = document.getElementById('video-passed'),
        timePicker = document.getElementById('timer-point-button'),
        videoAndControl = document.getElementById('video-and-control');

    var timeOut;
    var onePersent;

    playButton.onclick = function () {
        if (videoEl.paused) {
            videoEl.play();
        } else {
            videoEl.pause();
        }
    };

    videoEl.onclick = function () {
        if (videoEl.paused) {
            videoEl.play();
        } else {
            videoEl.pause();
        }
    };

    fullScreenButton.onclick = function () {
        if (videoContainer.classList.contains('full-screen')) {
            videoContainer.classList.remove('full-screen');
        } else {
            videoContainer.classList.add('full-screen');
        }
    };

    document.onclick = function (e) {
        e = e || event;
        target = e.target || e.srcElement;

        if (!videoContainer.classList.contains('full-screen') && target.id == "full-screen-button") {
            console.log(target.id);
        } else if (target.id == "video-container") {
            videoContainer.classList.remove('full-screen');
        }
    }

    window.onkeydown = (function (e) {
        if (e.keyCode === 27) {
            if (videoContainer.classList.contains('full-screen')) {
                videoContainer.classList.remove('full-screen');
            } else { }
            return false;
        }
    });

    timePicker.onmousedown = function (e) {

        onePersent = timeLine.getBoundingClientRect().width / 100;

        document.onmousemove = function (e) {
            moveAt(e.clientX - timeLine.getBoundingClientRect().left);
            return false;
        }

        document.onmouseup = function () {
            document.onmousemove = null;
            document.onmouseup = null;
        }

        return false;
    };

    timeLine.onmousedown = function (e) {

        showControlsElement();
        onePersent = timeLine.getBoundingClientRect().width / 100;
        moveAt(e.clientX - timeLine.getBoundingClientRect().left);

        return false;
    }

    function moveAt(newPosition) {
        if (newPosition <= 0) {
            newPosition = 0;
            timePicker.style.left = newPosition + 'px';
            videoEl.currentTime = newPosition * videoEl.duration / timeLine.getBoundingClientRect().width;

        } else if (newPosition >= timeLine.getBoundingClientRect().right - timeLine.getBoundingClientRect().left) {
            newPosition = timeLine.getBoundingClientRect().right - timeLine.getBoundingClientRect().left - onePersent;
            timePicker.style.left = newPosition + 'px';
            videoEl.currentTime = newPosition * videoEl.duration / timeLine.getBoundingClientRect().width;
        } else {
            timePicker.style.left = newPosition + 'px';
            videoEl.currentTime = newPosition * videoEl.duration / timeLine.getBoundingClientRect().width;
        }
    }

    function hideControlsElement() {
        //videoControls.style.display = 'none';
        videoControls.style.opacity ='0';
    }

    function showControlsElement() {
        //videoControls.style.display = 'flex';
        videoControls.style.opacity = '1';
    }

    videoEl.addEventListener('play', function () {

        playButton.style.backgroundImage = "url(../../Content/images/icons/pause-button.png)";

        videoAndControl.onmouseover = function (e) {
            showControlsElement();
        }        

        videoAndControl.onmouseout = function (e) {
            hideControlsElement();
        }

    }, false);


    videoEl.addEventListener('pause', function () {

        playButton.style.backgroundImage = "url(../../Content/images/icons/play-button.png)";
        videoAndControl.onmouseover = null;
        videoAndControl.onmouseout = null;
        showControlsElement();
    }, false);

    videoEl.addEventListener('ended', function () {

        videoEl.currentTime = 0;
        timePicker.style.left = '0%';
    }, false);

    videoEl.addEventListener('timeupdate', function () {

        timePicker.style.left = videoEl.currentTime / videoEl.duration * 100 + '%';
        videoPassed.style.width = videoEl.currentTime / videoEl.duration * 100 + '%';
    }, false);

</script>

KidsGenius/Views/Courses/CoursesList.cshtml
<div class="main-page-header-container">
    <button onclick="location.href='@Url.Action("Login", "Account")'" type="button" class="white-main-button">Kid Sign In</button>
    <p class="titleText">Kids genius</p>
</div>
<div class="youngerKids">


    <div class="brochure-courses-header">
        <div class="brochure-courses-header-info-subtitle">
            Good Starts
        </div>
        <div class="brochure-courses-header-wrapper">
            <div class="brochure-courses-header-info-component">
                <div class="brochure-courses-header-info-title" style="background-color: rgb(94, 219, 187);">
                    Younger Kids
                </div>
            </div>
            <div class="brochure-courses-header-meta-wrapper">
                <div class="brochure-courses-header-platforms">
                    <span class="brochure-courses-header-img-wrapper" style="background-color: rgb(94, 219, 187);">
                        <img src="https://d2ecljqfw49px2.cloudfront.net/assets/icons/devices.png" style="position: relative; top: 20%; height: 3vw; width: 3vw;" alt="">
                    </span>
                    <span>
                        iOS &amp; Web Browser
                    </span>
                </div>
                <div class="brochure-courses-header-age">
                    <span>
                        Ages 7-12
                    </span>
                    <span class="brochure-courses-header-img-wrapper" style="background-color: rgb(94, 219, 187);">
                        <img src="https://d2ecljqfw49px2.cloudfront.net/assets/icons/beginner.png" style="position: relative; top: 20%; height: 3vw; width: 3vw;" alt="">
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div id="div-wrapper">
        @foreach (var course in ViewBag.Courses)
        {
            <div id="single-div">
                <a href='@Url.Action("Course", "Courses", new { id = course.Id})'><img src="@course.MainPicture" /></a>
                <h3 class="course-name">@course.Name</h3>
                <p>@course.Description</p>
                <button class="submit white-button">@Html.ActionLink("Learn more...", "Course", new { id = course.Id })</button>
            </div>
        }
    </div>
</div>

<div class="olderKids">
    <div class="brochure-courses-header">
        <div class="brochure-courses-header-info-subtitle" style="color: rgb(255, 255, 255);">
            DEEP DIVES
        </div>
        <div class="brochure-courses-header-wrapper">
            <div class="brochure-courses-header-info-component">
                <div class="brochure-courses-header-info-title" style="background-color: rgb(255, 255, 255);">
                    Older Kids
                </div>
            </div>
            <div class="brochure-courses-header-meta-wrapper">
                <div class="brochure-courses-header-platforms">
                    <span class="brochure-courses-header-img-wrapper" style="background-color: rgb(255, 255, 255);">
                        <img src="https://d2ecljqfw49px2.cloudfront.net/assets/icons/devices.png" style="position: relative; top: 20%; height: 3vw; width: 3vw;" alt="">
                    </span>
                    <span style="color: rgb(255, 255, 255);">
                        iOS &amp; Web Browser
                    </span>
                </div>
                <div class="brochure-courses-header-age">
                    <span style="color: rgb(255, 255, 255);">
                        Ages 10-16
                    </span>
                    <span class="brochure-courses-header-img-wrapper" style="background-color: rgb(255, 255, 255);">
                        <img src="https://d2ecljqfw49px2.cloudfront.net/assets/icons/intermediate.png" style="position: relative; top: 20%; height: 3vw; width: 3vw;" alt="">
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div id="div-wrapper">
            @foreach (var course in ViewBag.Courses)
        {
            <div id="single-div">
                <div class="single-course-div">
                    <a href='@Url.Action("Course", "Courses", new { id = course.Id})'><img src="@course.MainPicture" /></a>
                    <h3 class="course-name">@course.Name</h3>
                    <p>@course.Description</p>
                    <button class="submit white-button">@Html.ActionLink("Learn more...", "Course", new { id = course.Id })</button>
                </div>
            </div>
    }
    </div>
</div>
<div class="workspaceDiv">
    <p class="workspaceP">
        GET MENTORSHIP ANYWHERE
        <br />
        How It Works
    </p>
</div>
<div class="brochure-segment-component left">
    <div class="inner-wrapper">
        <div class="brochure-info-segments">
            <div class="brochure-info-segment-component">
                <img src="https://d2ecljqfw49px2.cloudfront.net/assets/icons/video-meeting-chat-text.png" class="brochure-info-segment-icon" alt="">
                    <div class="brochure-info-segment-title">Video Based</div>
                        <div class="brochure-info-segment-description">
                            Each course contains a video library produced by our mentors demonstrating techniques, pro secrets and challenges.
                        </div>
             </div>
             <div class="brochure-info-segment-component">
                <img src="https://d2ecljqfw49px2.cloudfront.net/assets/icons/location-pin-direction.png" class="brochure-info-segment-icon" alt="">
                <div class="brochure-info-segment-title">Pick Your Own Path</div>
                <div class="brochure-info-segment-description">
                    Projects can be completed in any order and at any pace. Keeping momentum is our priority, even if it's slow and steady.
                </div>
             </div>
         </div>
         <div class="brochure-segment-content"></div>
     </div>
</div>
@helper ConsoleLog(string message)
    {
        var log = message;

        <script>
        if ( window.console && window.console.log ) {
            console.log("@log");
        }
        </script>
}