KidsGenius/Controllers/MyRoomController.cs
using KidsGenius.DAL;
using KidsGenius.Filters;
using KidsGenius.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace KidsGenius.Controllers
{
    [CustomAuthorize]
    public class MyRoomController : Controller
    {
        CourseContext courseDb = new CourseContext();
        
        public ActionResult MyCourses()
        {
            User user = courseDb.Users.FirstOrDefault(u => u.Email == User.Identity.Name);

            List<Course> userCourses = new List<Course>();

            foreach (UserCourses userCourse in courseDb.UsersCourses)
            {
                if (userCourse.UserId == user.Id)
                {
                    userCourses.Add(courseDb.Courses.FirstOrDefault(c => c.Id == userCourse.CourseId));
                }
            }

            if (userCourses == null)
            {

            }

            ViewBag.UserCourses = userCourses;

            return View();
        }

        public ActionResult Course(int? id)
        {


            return View();
        }

    }
}

KidsGenius/Views/MyRoom/MyCourses.cshtml
@{
    Layout = "~/Views/Shared/_MyRoomLayout.cshtml";
}

<div class="user-panel-container">
    <div class="logout-button">
        <button type="button" onclick="location.href='@Url.Action("LogOff", "Account")'" class="logout-button circle" style="height:80px; width: 80px;">Log Out</button>
        @*<a href='@Url.Action("LogOff", "Account")'>LogOut</a>*@
    </div>
</div>

<div>
    @foreach (var userCourse in ViewBag.UserCourses)
    {
        <div id="single-div">
            <a href='@Url.Action("Course", "MyRoom", new { id = userCourse.Id})'><img src="@userCourse.MainPicture" /></a>
            <h3>@userCourse.Name</h3>
            <p>@userCourse.Description</p>
        </div>
    }
</div>